### ISSUE TITLE
Need fix Wiki

### ISSUE THREAD

**Issue by onatsko** [Bardin08/X.Serilog.Sinks.Telegram#27]
**Describe the bug**
On page https://github.com/Bardin08/X.Serilog.Sinks.Telegram/wiki/Configuration we see this code example:
```
var logger = new LoggerConfiguration()
    .Telegram(config =>
    {
        config.Token = "your_telegram_bot_token";
      ...
```
but it didn't work

instead need:
```
                logConfig = new LoggerConfiguration()
                    .WriteTo.Telegram(config =>
                    {
                        config.Token = "your_telegram_bot_token";
                      ...
```

**Comment by Bardin08** [comment]
@onatsko thanks! I could reproduce this issue and will update the configuration section for the Wiki page now.

Kudos, Sir

**Comment by Bardin08** [comment]
The actual configuration examples are listed in the [5-th revision](https://github.com/Bardin08/X.Serilog.Sinks.Telegram/wiki/Configuration/0711ef9f20ccb90b38ed12ef21dc6981b1dc6685) of the Wiki page.
